/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: codec.i


extern
#ifdef __cplusplus
  "C"
#endif
  void cgo_panic__codec_cffb419519a4d845(const char*);
static void _swig_gopanic(const char *p) {
  cgo_panic__codec_cffb419519a4d845(p);
}



#define SWIG_VERSION 0x040101
#define SWIGGO
#define SWIGMODULE codec
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "codec.h"
#include "export.h"


#include <string>


#include <vector>
#include <stdexcept>

SWIGINTERN std::vector< std::string >::const_reference std_vector_Sl_std_string_Sg__get(std::vector< std::string > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_std_string_Sg__set(std::vector< std::string > *self,int i,std::vector< std::string >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN std::vector< char >::const_reference std_vector_Sl_char_Sg__get(std::vector< char > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_char_Sg__set(std::vector< char > *self,int i,std::vector< char >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }
#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_codec_cffb419519a4d845(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_codec_cffb419519a4d845(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


std::vector< std::string > *_wrap_new_StringVector__SWIG_0_codec_cffb419519a4d845() {
  std::vector< std::string > *result = 0 ;
  std::vector< std::string > *_swig_go_result;
  
  
  result = (std::vector< std::string > *)new std::vector< std::string >();
  *(std::vector< std::string > **)&_swig_go_result = (std::vector< std::string > *)result; 
  return _swig_go_result;
}


std::vector< std::string > *_wrap_new_StringVector__SWIG_1_codec_cffb419519a4d845(long long _swig_go_0) {
  std::vector< std::string >::size_type arg1 ;
  std::vector< std::string > *result = 0 ;
  std::vector< std::string > *_swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  
  result = (std::vector< std::string > *)new std::vector< std::string >(arg1);
  *(std::vector< std::string > **)&_swig_go_result = (std::vector< std::string > *)result; 
  return _swig_go_result;
}


std::vector< std::string > *_wrap_new_StringVector__SWIG_2_codec_cffb419519a4d845(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = 0 ;
  std::vector< std::string > *result = 0 ;
  std::vector< std::string > *_swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = (std::vector< std::string > *)new std::vector< std::string >((std::vector< std::string > const &)*arg1);
  *(std::vector< std::string > **)&_swig_go_result = (std::vector< std::string > *)result; 
  return _swig_go_result;
}


long long _wrap_StringVector_size_codec_cffb419519a4d845(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  std::vector< std::string >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = ((std::vector< std::string > const *)arg1)->size();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_StringVector_capacity_codec_cffb419519a4d845(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  std::vector< std::string >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = ((std::vector< std::string > const *)arg1)->capacity();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_StringVector_reserve_codec_cffb419519a4d845(std::vector< std::string > *_swig_go_0, long long _swig_go_1) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  std::vector< std::string >::size_type arg2 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  (arg1)->reserve(arg2);
  
}


bool _wrap_StringVector_isEmpty_codec_cffb419519a4d845(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = (bool)((std::vector< std::string > const *)arg1)->empty();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_StringVector_clear_codec_cffb419519a4d845(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  (arg1)->clear();
  
}


void _wrap_StringVector_add_codec_cffb419519a4d845(std::vector< std::string > *_swig_go_0, _gostring_ _swig_go_1) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  std::vector< std::string >::value_type *arg2 = 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  std::vector< std::string >::value_type arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  (arg1)->push_back((std::vector< std::string >::value_type const &)*arg2);
  
}


_gostring_ _wrap_StringVector_get_codec_cffb419519a4d845(std::vector< std::string > *_swig_go_0, intgo _swig_go_1) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  int arg2 ;
  std::vector< std::string >::value_type *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  try {
    result = (std::vector< std::string >::value_type *) &std_vector_Sl_std_string_Sg__get(arg1,arg2);
  } catch(std::out_of_range &_e) {
    (void)_e;
    _swig_gopanic("C++ std::out_of_range exception thrown");
    
  }
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_StringVector_set_codec_cffb419519a4d845(std::vector< std::string > *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  int arg2 ;
  std::vector< std::string >::value_type *arg3 = 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  std::vector< std::string >::value_type arg3_str(_swig_go_2.p, _swig_go_2.n);
  arg3 = &arg3_str;
  
  
  try {
    std_vector_Sl_std_string_Sg__set(arg1,arg2,(std::string const &)*arg3);
  } catch(std::out_of_range &_e) {
    (void)_e;
    _swig_gopanic("C++ std::out_of_range exception thrown");
    
  }
  
}


void _wrap_delete_StringVector_codec_cffb419519a4d845(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_new_ByteVector__SWIG_0_codec_cffb419519a4d845() {
  std::vector< char > *result = 0 ;
  std::vector< char > *_swig_go_result;
  
  
  result = (std::vector< char > *)new std::vector< char >();
  *(std::vector< char > **)&_swig_go_result = (std::vector< char > *)result; 
  return _swig_go_result;
}


std::vector< char > *_wrap_new_ByteVector__SWIG_1_codec_cffb419519a4d845(long long _swig_go_0) {
  std::vector< char >::size_type arg1 ;
  std::vector< char > *result = 0 ;
  std::vector< char > *_swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  
  result = (std::vector< char > *)new std::vector< char >(arg1);
  *(std::vector< char > **)&_swig_go_result = (std::vector< char > *)result; 
  return _swig_go_result;
}


std::vector< char > *_wrap_new_ByteVector__SWIG_2_codec_cffb419519a4d845(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = 0 ;
  std::vector< char > *result = 0 ;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  result = (std::vector< char > *)new std::vector< char >((std::vector< char > const &)*arg1);
  *(std::vector< char > **)&_swig_go_result = (std::vector< char > *)result; 
  return _swig_go_result;
}


long long _wrap_ByteVector_size_codec_cffb419519a4d845(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  std::vector< char >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  result = ((std::vector< char > const *)arg1)->size();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_ByteVector_capacity_codec_cffb419519a4d845(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  std::vector< char >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  result = ((std::vector< char > const *)arg1)->capacity();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_ByteVector_reserve_codec_cffb419519a4d845(std::vector< char > *_swig_go_0, long long _swig_go_1) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  std::vector< char >::size_type arg2 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  (arg1)->reserve(arg2);
  
}


bool _wrap_ByteVector_isEmpty_codec_cffb419519a4d845(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  result = (bool)((std::vector< char > const *)arg1)->empty();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_ByteVector_clear_codec_cffb419519a4d845(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  (arg1)->clear();
  
}


void _wrap_ByteVector_add_codec_cffb419519a4d845(std::vector< char > *_swig_go_0, char _swig_go_1) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  std::vector< char >::value_type *arg2 = 0 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  arg2 = (std::vector< char >::value_type *)&_swig_go_1; 
  
  (arg1)->push_back((std::vector< char >::value_type const &)*arg2);
  
}


char _wrap_ByteVector_get_codec_cffb419519a4d845(std::vector< char > *_swig_go_0, intgo _swig_go_1) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  int arg2 ;
  std::vector< char >::value_type *result = 0 ;
  char _swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  try {
    result = (std::vector< char >::value_type *) &std_vector_Sl_char_Sg__get(arg1,arg2);
  } catch(std::out_of_range &_e) {
    (void)_e;
    _swig_gopanic("C++ std::out_of_range exception thrown");
    
  }
  _swig_go_result = (char)*result; 
  return _swig_go_result;
}


void _wrap_ByteVector_set_codec_cffb419519a4d845(std::vector< char > *_swig_go_0, intgo _swig_go_1, char _swig_go_2) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  int arg2 ;
  std::vector< char >::value_type *arg3 = 0 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (std::vector< char >::value_type *)&_swig_go_2; 
  
  try {
    std_vector_Sl_char_Sg__set(arg1,arg2,(char const &)*arg3);
  } catch(std::out_of_range &_e) {
    (void)_e;
    _swig_gopanic("C++ std::out_of_range exception thrown");
    
  }
  
}


void _wrap_delete_ByteVector_codec_cffb419519a4d845(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_opj_input_memory_stream_pData_set_codec_cffb419519a4d845(opj_input_memory_stream *_swig_go_0, OPJ_UINT8 *_swig_go_1) {
  opj_input_memory_stream *arg1 = (opj_input_memory_stream *) 0 ;
  OPJ_UINT8 *arg2 = (OPJ_UINT8 *) 0 ;
  
  arg1 = *(opj_input_memory_stream **)&_swig_go_0; 
  arg2 = *(OPJ_UINT8 **)&_swig_go_1; 
  
  if (arg1) (arg1)->pData = arg2;
  
}


OPJ_UINT8 *_wrap_opj_input_memory_stream_pData_get_codec_cffb419519a4d845(opj_input_memory_stream *_swig_go_0) {
  opj_input_memory_stream *arg1 = (opj_input_memory_stream *) 0 ;
  OPJ_UINT8 *result = 0 ;
  OPJ_UINT8 *_swig_go_result;
  
  arg1 = *(opj_input_memory_stream **)&_swig_go_0; 
  
  result = (OPJ_UINT8 *) ((arg1)->pData);
  *(OPJ_UINT8 **)&_swig_go_result = (OPJ_UINT8 *)result; 
  return _swig_go_result;
}


void _wrap_opj_input_memory_stream_dataSize_set_codec_cffb419519a4d845(opj_input_memory_stream *_swig_go_0, OPJ_SIZE_T *_swig_go_1) {
  opj_input_memory_stream *arg1 = (opj_input_memory_stream *) 0 ;
  OPJ_SIZE_T arg2 ;
  OPJ_SIZE_T *argp2 ;
  
  arg1 = *(opj_input_memory_stream **)&_swig_go_0; 
  
  argp2 = (OPJ_SIZE_T *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null OPJ_SIZE_T");
  }
  arg2 = (OPJ_SIZE_T)*argp2;
  
  
  if (arg1) (arg1)->dataSize = arg2;
  
}


OPJ_SIZE_T *_wrap_opj_input_memory_stream_dataSize_get_codec_cffb419519a4d845(opj_input_memory_stream *_swig_go_0) {
  opj_input_memory_stream *arg1 = (opj_input_memory_stream *) 0 ;
  OPJ_SIZE_T result;
  OPJ_SIZE_T *_swig_go_result;
  
  arg1 = *(opj_input_memory_stream **)&_swig_go_0; 
  
  result =  ((arg1)->dataSize);
  *(OPJ_SIZE_T **)&_swig_go_result = new OPJ_SIZE_T(result); 
  return _swig_go_result;
}


void _wrap_opj_input_memory_stream_offset_set_codec_cffb419519a4d845(opj_input_memory_stream *_swig_go_0, OPJ_SIZE_T *_swig_go_1) {
  opj_input_memory_stream *arg1 = (opj_input_memory_stream *) 0 ;
  OPJ_SIZE_T arg2 ;
  OPJ_SIZE_T *argp2 ;
  
  arg1 = *(opj_input_memory_stream **)&_swig_go_0; 
  
  argp2 = (OPJ_SIZE_T *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null OPJ_SIZE_T");
  }
  arg2 = (OPJ_SIZE_T)*argp2;
  
  
  if (arg1) (arg1)->offset = arg2;
  
}


OPJ_SIZE_T *_wrap_opj_input_memory_stream_offset_get_codec_cffb419519a4d845(opj_input_memory_stream *_swig_go_0) {
  opj_input_memory_stream *arg1 = (opj_input_memory_stream *) 0 ;
  OPJ_SIZE_T result;
  OPJ_SIZE_T *_swig_go_result;
  
  arg1 = *(opj_input_memory_stream **)&_swig_go_0; 
  
  result =  ((arg1)->offset);
  *(OPJ_SIZE_T **)&_swig_go_result = new OPJ_SIZE_T(result); 
  return _swig_go_result;
}


opj_input_memory_stream *_wrap_new_opj_input_memory_stream_codec_cffb419519a4d845() {
  opj_input_memory_stream *result = 0 ;
  opj_input_memory_stream *_swig_go_result;
  
  
  result = (opj_input_memory_stream *)new opj_input_memory_stream();
  *(opj_input_memory_stream **)&_swig_go_result = (opj_input_memory_stream *)result; 
  return _swig_go_result;
}


void _wrap_delete_opj_input_memory_stream_codec_cffb419519a4d845(opj_input_memory_stream *_swig_go_0) {
  opj_input_memory_stream *arg1 = (opj_input_memory_stream *) 0 ;
  
  arg1 = *(opj_input_memory_stream **)&_swig_go_0; 
  
  delete arg1;
  
}


OPJ_BOOL *_wrap_opj_input_memory_stream_seek_codec_cffb419519a4d845(OPJ_OFF_T *_swig_go_0, void *_swig_go_1) {
  OPJ_OFF_T arg1 ;
  void *arg2 = (void *) 0 ;
  OPJ_OFF_T *argp1 ;
  OPJ_BOOL result;
  OPJ_BOOL *_swig_go_result;
  
  
  argp1 = (OPJ_OFF_T *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null OPJ_OFF_T");
  }
  arg1 = (OPJ_OFF_T)*argp1;
  
  arg2 = *(void **)&_swig_go_1; 
  
  result = opj_input_memory_stream_seek(SWIG_STD_MOVE(arg1),arg2);
  *(OPJ_BOOL **)&_swig_go_result = new OPJ_BOOL(result); 
  return _swig_go_result;
}


OPJ_OFF_T *_wrap_opj_input_memory_stream_skip_codec_cffb419519a4d845(OPJ_OFF_T *_swig_go_0, void *_swig_go_1) {
  OPJ_OFF_T arg1 ;
  void *arg2 = (void *) 0 ;
  OPJ_OFF_T *argp1 ;
  OPJ_OFF_T result;
  OPJ_OFF_T *_swig_go_result;
  
  
  argp1 = (OPJ_OFF_T *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null OPJ_OFF_T");
  }
  arg1 = (OPJ_OFF_T)*argp1;
  
  arg2 = *(void **)&_swig_go_1; 
  
  result = opj_input_memory_stream_skip(SWIG_STD_MOVE(arg1),arg2);
  *(OPJ_OFF_T **)&_swig_go_result = new OPJ_OFF_T(result); 
  return _swig_go_result;
}


OPJ_SIZE_T *_wrap_opj_input_memory_stream_read_codec_cffb419519a4d845(void *_swig_go_0, OPJ_SIZE_T *_swig_go_1, void *_swig_go_2) {
  void *arg1 = (void *) 0 ;
  OPJ_SIZE_T arg2 ;
  void *arg3 = (void *) 0 ;
  OPJ_SIZE_T *argp2 ;
  OPJ_SIZE_T result;
  OPJ_SIZE_T *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  argp2 = (OPJ_SIZE_T *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null OPJ_SIZE_T");
  }
  arg2 = (OPJ_SIZE_T)*argp2;
  
  arg3 = *(void **)&_swig_go_2; 
  
  result = opj_input_memory_stream_read(arg1,SWIG_STD_MOVE(arg2),arg3);
  *(OPJ_SIZE_T **)&_swig_go_result = new OPJ_SIZE_T(result); 
  return _swig_go_result;
}


void _wrap_opj_output_memory_stream_chunk_data_set_codec_cffb419519a4d845(opj_output_memory_stream_chunk *_swig_go_0, OPJ_UINT8 *_swig_go_1) {
  opj_output_memory_stream_chunk *arg1 = (opj_output_memory_stream_chunk *) 0 ;
  OPJ_UINT8 *arg2 = (OPJ_UINT8 *) 0 ;
  
  arg1 = *(opj_output_memory_stream_chunk **)&_swig_go_0; 
  arg2 = *(OPJ_UINT8 **)&_swig_go_1; 
  
  if (arg1) (arg1)->data = arg2;
  
}


OPJ_UINT8 *_wrap_opj_output_memory_stream_chunk_data_get_codec_cffb419519a4d845(opj_output_memory_stream_chunk *_swig_go_0) {
  opj_output_memory_stream_chunk *arg1 = (opj_output_memory_stream_chunk *) 0 ;
  OPJ_UINT8 *result = 0 ;
  OPJ_UINT8 *_swig_go_result;
  
  arg1 = *(opj_output_memory_stream_chunk **)&_swig_go_0; 
  
  result = (OPJ_UINT8 *) ((arg1)->data);
  *(OPJ_UINT8 **)&_swig_go_result = (OPJ_UINT8 *)result; 
  return _swig_go_result;
}


void _wrap_opj_output_memory_stream_chunk_dataLen_set_codec_cffb419519a4d845(opj_output_memory_stream_chunk *_swig_go_0, OPJ_SIZE_T *_swig_go_1) {
  opj_output_memory_stream_chunk *arg1 = (opj_output_memory_stream_chunk *) 0 ;
  OPJ_SIZE_T arg2 ;
  OPJ_SIZE_T *argp2 ;
  
  arg1 = *(opj_output_memory_stream_chunk **)&_swig_go_0; 
  
  argp2 = (OPJ_SIZE_T *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null OPJ_SIZE_T");
  }
  arg2 = (OPJ_SIZE_T)*argp2;
  
  
  if (arg1) (arg1)->dataLen = arg2;
  
}


OPJ_SIZE_T *_wrap_opj_output_memory_stream_chunk_dataLen_get_codec_cffb419519a4d845(opj_output_memory_stream_chunk *_swig_go_0) {
  opj_output_memory_stream_chunk *arg1 = (opj_output_memory_stream_chunk *) 0 ;
  OPJ_SIZE_T result;
  OPJ_SIZE_T *_swig_go_result;
  
  arg1 = *(opj_output_memory_stream_chunk **)&_swig_go_0; 
  
  result =  ((arg1)->dataLen);
  *(OPJ_SIZE_T **)&_swig_go_result = new OPJ_SIZE_T(result); 
  return _swig_go_result;
}


opj_output_memory_stream_chunk *_wrap_new_opj_output_memory_stream_chunk_codec_cffb419519a4d845() {
  opj_output_memory_stream_chunk *result = 0 ;
  opj_output_memory_stream_chunk *_swig_go_result;
  
  
  result = (opj_output_memory_stream_chunk *)new opj_output_memory_stream_chunk();
  *(opj_output_memory_stream_chunk **)&_swig_go_result = (opj_output_memory_stream_chunk *)result; 
  return _swig_go_result;
}


void _wrap_delete_opj_output_memory_stream_chunk_codec_cffb419519a4d845(opj_output_memory_stream_chunk *_swig_go_0) {
  opj_output_memory_stream_chunk *arg1 = (opj_output_memory_stream_chunk *) 0 ;
  
  arg1 = *(opj_output_memory_stream_chunk **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_opj_output_memory_stream_dataSize_set_codec_cffb419519a4d845(opj_output_memory_stream *_swig_go_0, OPJ_SIZE_T *_swig_go_1) {
  opj_output_memory_stream *arg1 = (opj_output_memory_stream *) 0 ;
  OPJ_SIZE_T arg2 ;
  OPJ_SIZE_T *argp2 ;
  
  arg1 = *(opj_output_memory_stream **)&_swig_go_0; 
  
  argp2 = (OPJ_SIZE_T *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null OPJ_SIZE_T");
  }
  arg2 = (OPJ_SIZE_T)*argp2;
  
  
  if (arg1) (arg1)->dataSize = arg2;
  
}


OPJ_SIZE_T *_wrap_opj_output_memory_stream_dataSize_get_codec_cffb419519a4d845(opj_output_memory_stream *_swig_go_0) {
  opj_output_memory_stream *arg1 = (opj_output_memory_stream *) 0 ;
  OPJ_SIZE_T result;
  OPJ_SIZE_T *_swig_go_result;
  
  arg1 = *(opj_output_memory_stream **)&_swig_go_0; 
  
  result =  ((arg1)->dataSize);
  *(OPJ_SIZE_T **)&_swig_go_result = new OPJ_SIZE_T(result); 
  return _swig_go_result;
}


void _wrap_opj_output_memory_stream_chunks_set_codec_cffb419519a4d845(opj_output_memory_stream *_swig_go_0, std::vector< opj_output_memory_stream_chunk > *_swig_go_1) {
  opj_output_memory_stream *arg1 = (opj_output_memory_stream *) 0 ;
  std::vector< opj_output_memory_stream_chunk > *arg2 = (std::vector< opj_output_memory_stream_chunk > *) 0 ;
  
  arg1 = *(opj_output_memory_stream **)&_swig_go_0; 
  arg2 = *(std::vector< opj_output_memory_stream_chunk > **)&_swig_go_1; 
  
  if (arg1) (arg1)->chunks = *arg2;
  
}


std::vector< opj_output_memory_stream_chunk > *_wrap_opj_output_memory_stream_chunks_get_codec_cffb419519a4d845(opj_output_memory_stream *_swig_go_0) {
  opj_output_memory_stream *arg1 = (opj_output_memory_stream *) 0 ;
  std::vector< opj_output_memory_stream_chunk > *result = 0 ;
  std::vector< opj_output_memory_stream_chunk > *_swig_go_result;
  
  arg1 = *(opj_output_memory_stream **)&_swig_go_0; 
  
  result = (std::vector< opj_output_memory_stream_chunk > *)& ((arg1)->chunks);
  *(std::vector< opj_output_memory_stream_chunk > **)&_swig_go_result = (std::vector< opj_output_memory_stream_chunk > *)result; 
  return _swig_go_result;
}


opj_output_memory_stream *_wrap_new_opj_output_memory_stream_codec_cffb419519a4d845() {
  opj_output_memory_stream *result = 0 ;
  opj_output_memory_stream *_swig_go_result;
  
  
  result = (opj_output_memory_stream *)new opj_output_memory_stream();
  *(opj_output_memory_stream **)&_swig_go_result = (opj_output_memory_stream *)result; 
  return _swig_go_result;
}


void _wrap_delete_opj_output_memory_stream_codec_cffb419519a4d845(opj_output_memory_stream *_swig_go_0) {
  opj_output_memory_stream *arg1 = (opj_output_memory_stream *) 0 ;
  
  arg1 = *(opj_output_memory_stream **)&_swig_go_0; 
  
  delete arg1;
  
}


OPJ_BOOL *_wrap_opj_output_memory_stream_seek_codec_cffb419519a4d845(OPJ_OFF_T *_swig_go_0, void *_swig_go_1) {
  OPJ_OFF_T arg1 ;
  void *arg2 = (void *) 0 ;
  OPJ_OFF_T *argp1 ;
  OPJ_BOOL result;
  OPJ_BOOL *_swig_go_result;
  
  
  argp1 = (OPJ_OFF_T *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null OPJ_OFF_T");
  }
  arg1 = (OPJ_OFF_T)*argp1;
  
  arg2 = *(void **)&_swig_go_1; 
  
  result = opj_output_memory_stream_seek(SWIG_STD_MOVE(arg1),arg2);
  *(OPJ_BOOL **)&_swig_go_result = new OPJ_BOOL(result); 
  return _swig_go_result;
}


OPJ_OFF_T *_wrap_opj_output_memory_stream_skip_codec_cffb419519a4d845(OPJ_OFF_T *_swig_go_0, void *_swig_go_1) {
  OPJ_OFF_T arg1 ;
  void *arg2 = (void *) 0 ;
  OPJ_OFF_T *argp1 ;
  OPJ_OFF_T result;
  OPJ_OFF_T *_swig_go_result;
  
  
  argp1 = (OPJ_OFF_T *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null OPJ_OFF_T");
  }
  arg1 = (OPJ_OFF_T)*argp1;
  
  arg2 = *(void **)&_swig_go_1; 
  
  result = opj_output_memory_stream_skip(SWIG_STD_MOVE(arg1),arg2);
  *(OPJ_OFF_T **)&_swig_go_result = new OPJ_OFF_T(result); 
  return _swig_go_result;
}


OPJ_SIZE_T *_wrap_opj_output_memory_stream_write_codec_cffb419519a4d845(void *_swig_go_0, OPJ_SIZE_T *_swig_go_1, void *_swig_go_2) {
  void *arg1 = (void *) 0 ;
  OPJ_SIZE_T arg2 ;
  void *arg3 = (void *) 0 ;
  OPJ_SIZE_T *argp2 ;
  OPJ_SIZE_T result;
  OPJ_SIZE_T *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  
  argp2 = (OPJ_SIZE_T *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null OPJ_SIZE_T");
  }
  arg2 = (OPJ_SIZE_T)*argp2;
  
  arg3 = *(void **)&_swig_go_2; 
  
  result = opj_output_memory_stream_write(arg1,SWIG_STD_MOVE(arg2),arg3);
  *(OPJ_SIZE_T **)&_swig_go_result = new OPJ_SIZE_T(result); 
  return _swig_go_result;
}


char *_wrap_J2K_Decode_codec_cffb419519a4d845(char *_swig_go_0, long long _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, long long *_swig_go_4) {
  unsigned char *arg1 = (unsigned char *) 0 ;
  size_t arg2 ;
  int arg3 ;
  int arg4 ;
  size_t *arg5 = (size_t *) 0 ;
  unsigned char *result = 0 ;
  char *_swig_go_result;
  
  arg1 = *(unsigned char **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(size_t **)&_swig_go_4; 
  
  result = (unsigned char *)J2K_Decode(arg1,SWIG_STD_MOVE(arg2),arg3,arg4,arg5);
  *(unsigned char **)&_swig_go_result = (unsigned char *)result; 
  return _swig_go_result;
}


char *_wrap_JPEG_Decode_codec_cffb419519a4d845(char *_swig_go_0, long long _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, intgo _swig_go_4, intgo _swig_go_5, intgo _swig_go_6, intgo _swig_go_7, long long *_swig_go_8) {
  unsigned char *arg1 = (unsigned char *) 0 ;
  size_t arg2 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  int arg6 ;
  int arg7 ;
  int arg8 ;
  size_t *arg9 = (size_t *) 0 ;
  unsigned char *result = 0 ;
  char *_swig_go_result;
  
  arg1 = *(unsigned char **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = (int)_swig_go_4; 
  arg6 = (int)_swig_go_5; 
  arg7 = (int)_swig_go_6; 
  arg8 = (int)_swig_go_7; 
  arg9 = *(size_t **)&_swig_go_8; 
  
  result = (unsigned char *)JPEG_Decode(arg1,SWIG_STD_MOVE(arg2),arg3,arg4,arg5,arg6,arg7,arg8,arg9);
  *(unsigned char **)&_swig_go_result = (unsigned char *)result; 
  return _swig_go_result;
}


char *_wrap_JPEGLS_Decode_codec_cffb419519a4d845(char *_swig_go_0, long long _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, intgo _swig_go_4, intgo _swig_go_5, intgo _swig_go_6, long long *_swig_go_7) {
  unsigned char *arg1 = (unsigned char *) 0 ;
  size_t arg2 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  int arg6 ;
  int arg7 ;
  size_t *arg8 = (size_t *) 0 ;
  unsigned char *result = 0 ;
  char *_swig_go_result;
  
  arg1 = *(unsigned char **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = (int)_swig_go_4; 
  arg6 = (int)_swig_go_5; 
  arg7 = (int)_swig_go_6; 
  arg8 = *(size_t **)&_swig_go_7; 
  
  result = (unsigned char *)JPEGLS_Decode(arg1,SWIG_STD_MOVE(arg2),arg3,arg4,arg5,arg6,arg7,arg8);
  *(unsigned char **)&_swig_go_result = (unsigned char *)result; 
  return _swig_go_result;
}


char *_wrap_J2K_Encode_codec_cffb419519a4d845(char *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, intgo _swig_go_4, intgo _swig_go_5, long long *_swig_go_6) {
  unsigned char *arg1 = (unsigned char *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  int arg6 ;
  size_t *arg7 = (size_t *) 0 ;
  unsigned char *result = 0 ;
  char *_swig_go_result;
  
  arg1 = *(unsigned char **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = (int)_swig_go_4; 
  arg6 = (int)_swig_go_5; 
  arg7 = *(size_t **)&_swig_go_6; 
  
  result = (unsigned char *)J2K_Encode(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  *(unsigned char **)&_swig_go_result = (unsigned char *)result; 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

